import type { Object3D } from "three"
import { VRMLLoader } from "three-stdlib"

/**
 * Replace hyphens in VRML DEF/USE identifiers with underscores.
 * This makes VRML files generated by KiCad compatible with the VRML parser
 * from three-stdlib which does not allow hyphens in identifiers.
 */
export function sanitizeVrmlIdentifiers(text: string): string {
  return text.replace(/(DEF|USE)\s+([^\s]+)/g, (match, type, name) => {
    return `${type} ${name.replace(/-/g, "_")}`
  })
}

/**
 * Fetch a VRML file and parse it into a THREE.Object3D, applying identifier
 * sanitization so that files with hyphenated DEF/USE names can be loaded.
 */
export async function loadVrml(url: string): Promise<Object3D> {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(
      `Failed to fetch "${url}": ${response.status} ${response.statusText}`,
    )
  }
  const text = await response.text()
  const loader = new VRMLLoader()
  return loader.parse(sanitizeVrmlIdentifiers(text))
}
