import { CadViewer } from "src"
import type { Meta, StoryObj } from "@storybook/react"

const meta = {
  title: "Bugs/Circle Plated Hole",
  component: CadViewer,
  parameters: {
    layout: "fullscreen",
  },
} satisfies Meta<typeof CadViewer>

export default meta
type Story = StoryObj<typeof meta>

export const CirclePlatedHole: Story = {
  args: {
    circuitJson: [
      {
        type: "source_project_metadata",
        source_project_metadata_id: "source_project_metadata_0",
        software_used_string: "@tscircuit/core@0.0.807",
      },
      {
        type: "source_group",
        source_group_id: "source_group_0",
        is_subcircuit: true,
        was_automatically_named: true,
        subcircuit_id: "subcircuit_source_group_0",
      },
      {
        type: "source_port",
        source_port_id: "source_port_0",
        name: "pin1",
        pin_number: 1,
        port_hints: ["pin1", "1"],
        source_component_id: "source_component_0",
        subcircuit_id: "subcircuit_source_group_0",
      },
      {
        type: "source_component",
        source_component_id: "source_component_0",
        ftype: "simple_chip",
        name: "MP1",
        supplier_part_numbers: {
          jlcpcb: [],
        },
        source_group_id: "source_group_0",
      },
      {
        type: "source_port",
        source_port_id: "source_port_1",
        name: "pin1",
        pin_number: 1,
        port_hints: ["pin1", "1"],
        source_component_id: "source_component_1",
        subcircuit_id: "subcircuit_source_group_0",
      },
      {
        type: "source_component",
        source_component_id: "source_component_1",
        ftype: "simple_chip",
        name: "MP2",
        supplier_part_numbers: {
          jlcpcb: [],
        },
        source_group_id: "source_group_0",
      },
      {
        type: "source_board",
        source_board_id: "source_board_0",
        source_group_id: "source_group_0",
      },
      {
        source_port_id: "source_port_0",
        facing_direction: "left",
        distance_from_component_edge: 0.4,
        side_of_component: "left",
        pin_number: 1,
        true_ccw_index: 0,
        is_connected: false,
      },
      {
        type: "pcb_component",
        pcb_component_id: "pcb_component_0",
        center: {
          x: -1,
          y: 0,
        },
        width: 1.6,
        height: 1.6,
        layer: "top",
        rotation: 0,
        source_component_id: "source_component_0",
        subcircuit_id: "subcircuit_source_group_0",
        do_not_place: false,
        obstructs_within_bounds: true,
      },
      {
        type: "pcb_component",
        pcb_component_id: "pcb_component_1",
        center: {
          x: 1,
          y: 0,
        },
        width: 1.6,
        height: 1.6,
        layer: "top",
        rotation: 0,
        source_component_id: "source_component_1",
        subcircuit_id: "subcircuit_source_group_0",
        do_not_place: false,
        obstructs_within_bounds: true,
      },
      {
        type: "pcb_board",
        pcb_board_id: "pcb_board_0",
        center: {
          x: 0,
          y: 0,
        },
        thickness: 1.4,
        num_layers: 2,
        width: 4,
        height: 2,
        material: "fr4",
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "pcb_plated_hole_0",
        pcb_component_id: "pcb_component_0",
        pcb_port_id: "pcb_port_0",
        outer_diameter: 1.6,
        hole_diameter: 1.2,
        shape: "circle",
        port_hints: ["unnamed_platedhole1", "1"],
        x: -1,
        y: 0,
        layers: ["top", "bottom"],
        subcircuit_id: "subcircuit_source_group_0",
      },
      {
        type: "pcb_silkscreen_text",
        pcb_silkscreen_text_id: "pcb_silkscreen_text_0",
        anchor_alignment: "center",
        anchor_position: {
          x: -1,
          y: 0,
        },
        font: "tscircuit2024",
        font_size: 0.5,
        layer: "top",
        text: "MP1",
        ccw_rotation: 0,
        pcb_component_id: "pcb_component_0",
        subcircuit_id: "subcircuit_source_group_0",
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "pcb_plated_hole_1",
        pcb_component_id: "pcb_component_1",
        pcb_port_id: "pcb_port_1",
        outer_diameter: 1.6,
        hole_diameter: 1.2,
        shape: "circle",
        port_hints: ["unnamed_platedhole2", "1"],
        x: 1,
        y: 0,
        layers: ["top", "bottom"],
        subcircuit_id: "subcircuit_source_group_0",
      },
      {
        type: "pcb_silkscreen_text",
        pcb_silkscreen_text_id: "pcb_silkscreen_text_1",
        anchor_alignment: "center",
        anchor_position: {
          x: 1,
          y: 0,
        },
        font: "tscircuit2024",
        font_size: 0.5,
        layer: "top",
        text: "MP2",
        ccw_rotation: 0,
        pcb_component_id: "pcb_component_1",
        subcircuit_id: "subcircuit_source_group_0",
      },
      {
        type: "pcb_port",
        pcb_port_id: "pcb_port_0",
        pcb_component_id: "pcb_component_0",
        layers: ["top", "inner1", "inner2", "bottom"],
        subcircuit_id: "subcircuit_source_group_0",
        x: -1,
        y: 0,
        source_port_id: "source_port_0",
      },
      {
        type: "pcb_port",
        pcb_port_id: "pcb_port_1",
        pcb_component_id: "pcb_component_1",
        layers: ["top", "inner1", "inner2", "bottom"],
        subcircuit_id: "subcircuit_source_group_0",
        x: 1,
        y: 0,
        source_port_id: "source_port_1",
      },
    ],
  },
}
