import { CadViewer } from "src/CadViewer"

const fabricationNoteRectCircuit = [
  {
    type: "pcb_board",
    pcb_board_id: "pcb_board_1",
    center: { x: 0, y: 0 },
    width: 15,
    height: 8,
    thickness: 1,
    num_layers: 2,
    material: "fr4",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_1",
    center: { x: 0, y: 0 },
    width: 0,
    height: 0,
    rotation: 0,
    layer: "top",
    obstructs_within_bounds: false,
    do_not_place: true,
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_bottom",
    center: { x: 0, y: 0 },
    width: 0,
    height: 0,
    rotation: 0,
    layer: "bottom",
    obstructs_within_bounds: false,
    do_not_place: true,
  },
  {
    type: "pcb_fabrication_note_rect",
    pcb_fabrication_note_rect_id: "pcb_fabrication_note_rect_filled",
    pcb_component_id: "pcb_component_1",
    center: { x: -2, y: 1.5 },
    width: "3mm",
    height: "2mm",
    layer: "top",
    stroke_width: "0.15mm",
    corner_radius: "0.4mm",
    is_filled: true,
    has_stroke: false,
  },
  {
    type: "pcb_fabrication_note_rect",
    pcb_fabrication_note_rect_id: "pcb_fabrication_note_rect_stroke",
    pcb_component_id: "pcb_component_1",
    center: { x: 0, y: -1 },
    width: "4mm",
    height: "2.2mm",
    layer: "top",
    stroke_width: "0.2mm",
    corner_radius: "0.5mm",
    is_filled: false,
    has_stroke: true,
  },
  {
    type: "pcb_fabrication_note_rect",
    pcb_fabrication_note_rect_id: "pcb_fabrication_note_rect_bottom",
    pcb_component_id: "pcb_component_bottom",
    center: { x: 0, y: 0 },
    width: "3mm",
    height: "3mm",
    layer: "bottom",
    stroke_width: "0.15mm",
    is_filled: true,
    has_stroke: true,
    corner_radius: "0.6mm",
  },
  {
    type: "pcb_fabrication_note_rect",
    pcb_fabrication_note_rect_id: "pcb_fabrication_note_rect_colored",
    pcb_component_id: "pcb_component_1",
    center: { x: 2.5, y: 1.5 },
    width: "2.5mm",
    height: "1.8mm",
    layer: "top",
    stroke_width: "0.1mm",
    corner_radius: "0.3mm",
    is_filled: true,
    has_stroke: true,
    color: "#FF6B6B",
  },
  {
    type: "pcb_fabrication_note_rect",
    pcb_fabrication_note_rect_id: "pcb_fabrication_note_rect_dashed",
    pcb_component_id: "pcb_component_1",
    center: { x: 4, y: -1 },
    width: "3mm",
    height: "1.5mm",
    layer: "top",
    stroke_width: "0.15mm",
    corner_radius: "0.2mm",
    is_filled: false,
    has_stroke: true,
    is_stroke_dashed: true,
    color: "#4ECDC4",
  },
  {
    type: "pcb_fabrication_note_rect",
    pcb_fabrication_note_rect_id: "pcb_fabrication_note_rect_no_radius",
    pcb_component_id: "pcb_component_1",
    center: { x: -4, y: -1 },
    width: "2mm",
    height: "2mm",
    layer: "top",
    stroke_width: "0.1mm",
    is_filled: true,
    has_stroke: true,
  },
]

export const FabricationNoteRectangles = () => (
  <CadViewer circuitJson={fabricationNoteRectCircuit as any} />
)

export default {
  title: "Fabrication Note Rect",
  component: FabricationNoteRectangles,
}
