import { CadViewer } from "src/CadViewer"

const pcbNoteLineCircuit = [
  {
    type: "pcb_board",
    pcb_board_id: "pcb_board_1",
    center: { x: 0, y: 0 },
    width: 15,
    height: 8,
    thickness: 1,
    num_layers: 2,
    material: "fr4",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_1",
    center: { x: 0, y: 0 },
    width: 0,
    height: 0,
    rotation: 0,
    layer: "top",
    obstructs_within_bounds: false,
    do_not_place: true,
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_bottom",
    center: { x: 0, y: 0 },
    width: 0,
    height: 0,
    rotation: 0,
    layer: "bottom",
    obstructs_within_bounds: false,
    do_not_place: true,
  },
  {
    type: "pcb_note_line",
    pcb_note_line_id: "pcb_note_line_1",
    pcb_component_id: "pcb_component_1",
    x1: "-3mm",
    y1: "2mm",
    x2: "-1mm",
    y2: "2mm",
    stroke_width: "0.15mm",
    layer: "top",
  },
  {
    type: "pcb_note_line",
    pcb_note_line_id: "pcb_note_line_2",
    pcb_component_id: "pcb_component_1",
    x1: "-3mm",
    y1: "1mm",
    x2: "-1mm",
    y2: "1mm",
    stroke_width: "0.2mm",
    layer: "top",
    color: "#FF6B6B",
  },
  {
    type: "pcb_note_line",
    pcb_note_line_id: "pcb_note_line_3",
    pcb_component_id: "pcb_component_1",
    x1: "-3mm",
    y1: "0mm",
    x2: "-1mm",
    y2: "0mm",
    stroke_width: "0.15mm",
    layer: "top",
    is_dashed: true,
  },
  {
    type: "pcb_note_line",
    pcb_note_line_id: "pcb_note_line_4",
    pcb_component_id: "pcb_component_1",
    x1: "-3mm",
    y1: "-1mm",
    x2: "-1mm",
    y2: "-1mm",
    stroke_width: "0.15mm",
    layer: "top",
    is_dashed: true,
    color: "#4ECDC4",
  },
  {
    type: "pcb_note_line",
    pcb_note_line_id: "pcb_note_line_5",
    pcb_component_id: "pcb_component_1",
    x1: "1mm",
    y1: "2mm",
    x2: "3mm",
    y2: "0mm",
    stroke_width: "0.1mm",
    layer: "top",
  },
  {
    type: "pcb_note_line",
    pcb_note_line_id: "pcb_note_line_6",
    pcb_component_id: "pcb_component_1",
    x1: "1mm",
    y1: "0mm",
    x2: "3mm",
    y2: "-2mm",
    stroke_width: "0.1mm",
    layer: "top",
    color: "#9B59B6",
  },
  {
    type: "pcb_note_line",
    pcb_note_line_id: "pcb_note_line_7",
    pcb_component_id: "pcb_component_1",
    x1: "4mm",
    y1: "2mm",
    x2: "6mm",
    y2: "2mm",
    stroke_width: "0.2mm",
    layer: "top",
    is_dashed: true,
    color: "#E67E22",
  },
  {
    type: "pcb_note_line",
    pcb_note_line_id: "pcb_note_line_bottom",
    pcb_component_id: "pcb_component_bottom",
    x1: "0mm",
    y1: "0mm",
    x2: "2mm",
    y2: "2mm",
    stroke_width: "0.15mm",
    layer: "bottom",
  },
  {
    type: "pcb_note_line",
    pcb_note_line_id: "pcb_note_line_bottom_dashed",
    pcb_component_id: "pcb_component_bottom",
    x1: "-2mm",
    y1: "0mm",
    x2: "0mm",
    y2: "2mm",
    stroke_width: "0.15mm",
    layer: "bottom",
    is_dashed: true,
    color: "#3498DB",
  },
]

export const PcbNoteLines = () => (
  <CadViewer circuitJson={pcbNoteLineCircuit as any} />
)

export default {
  title: "PCB Note Line",
  component: PcbNoteLines,
}
