import { CadViewer } from "../src/CadViewer"
import type { Meta, StoryObj } from "@storybook/react"

const meta = {
  title: "PCB/Rotated Pill Hole with Rect Pad",
  component: CadViewer,
  parameters: {
    layout: "fullscreen",
  },
} satisfies Meta<typeof CadViewer>

export default meta
type Story = StoryObj<typeof meta>

export const MultipleRotatedPillHoles: Story = {
  args: {
    circuitJson: [
      {
        type: "pcb_board",
        pcb_board_id: "board_1",
        thickness: 1.6,
        num_layers: 2,
        center: { x: 0, y: 0 },
        width: 80,
        height: 60,
        material: "fr4",
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "rotated-pill-0",
        x: -20,
        y: 15,
        shape: "rotated_pill_hole_with_rect_pad",
        hole_shape: "rotated_pill",
        pad_shape: "rect",
        hole_width: 3,
        hole_height: 1.5,
        hole_ccw_rotation: 0,
        rect_pad_width: 5,
        rect_pad_height: 3,
        rect_ccw_rotation: 0,
        hole_offset_x: 0,
        hole_offset_y: 0,
        layers: ["top", "bottom"],
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "rotated-pill-1",
        x: 0,
        y: 15,
        shape: "rotated_pill_hole_with_rect_pad",
        hole_shape: "rotated_pill",
        pad_shape: "rect",
        hole_width: 3,
        hole_height: 1.5,
        hole_ccw_rotation: 45,
        rect_pad_width: 5,
        rect_pad_height: 3,
        rect_ccw_rotation: 0,
        hole_offset_x: 0,
        hole_offset_y: 0,
        layers: ["top", "bottom"],
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "rotated-pill-2",
        x: 20,
        y: 15,
        shape: "rotated_pill_hole_with_rect_pad",
        hole_shape: "rotated_pill",
        pad_shape: "rect",
        hole_width: 3,
        hole_height: 1.5,
        hole_ccw_rotation: 90,
        rect_pad_width: 5,
        rect_pad_height: 3,
        rect_ccw_rotation: 0,
        hole_offset_x: 0,
        hole_offset_y: 0,
        layers: ["top", "bottom"],
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "rotated-pill-3",
        x: -20,
        y: 0,
        shape: "rotated_pill_hole_with_rect_pad",
        hole_shape: "rotated_pill",
        pad_shape: "rect",
        hole_width: 2.5,
        hole_height: 1.2,
        hole_ccw_rotation: 30,
        rect_pad_width: 4.5,
        rect_pad_height: 3.5,
        rect_ccw_rotation: 15,
        hole_offset_x: 0.5,
        hole_offset_y: 0,
        layers: ["top", "bottom"],
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "rotated-pill-4",
        x: 0,
        y: 0,
        shape: "rotated_pill_hole_with_rect_pad",
        hole_shape: "rotated_pill",
        pad_shape: "rect",
        hole_width: 2.5,
        hole_height: 1.2,
        hole_ccw_rotation: 30,
        rect_pad_width: 4.5,
        rect_pad_height: 3.5,
        rect_ccw_rotation: 60,
        hole_offset_x: 0,
        hole_offset_y: 0.5,
        layers: ["top", "bottom"],
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "rotated-pill-5",
        x: 20,
        y: 0,
        shape: "rotated_pill_hole_with_rect_pad",
        hole_shape: "rotated_pill",
        pad_shape: "rect",
        hole_width: 2,
        hole_height: 1,
        hole_ccw_rotation: 45,
        rect_pad_width: 5,
        rect_pad_height: 3,
        rect_ccw_rotation: 45,
        hole_offset_x: 0,
        hole_offset_y: 0.3,
        layers: ["top", "bottom"],
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "rotated-pill-6",
        x: -20,
        y: -15,
        shape: "rotated_pill_hole_with_rect_pad",
        hole_shape: "rotated_pill",
        pad_shape: "rect",
        hole_width: 2,
        hole_height: 1,
        hole_ccw_rotation: 0,
        rect_pad_width: 4,
        rect_pad_height: 3,
        rect_ccw_rotation: 30,
        rect_border_radius: 0.5,
        hole_offset_x: 0,
        hole_offset_y: 0,
        layers: ["top", "bottom"],
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "rotated-pill-7",
        x: 0,
        y: -15,
        shape: "rotated_pill_hole_with_rect_pad",
        hole_shape: "rotated_pill",
        pad_shape: "rect",
        hole_width: 2,
        hole_height: 1,
        hole_ccw_rotation: 60,
        rect_pad_width: 4,
        rect_pad_height: 3,
        rect_ccw_rotation: 30,
        rect_border_radius: 0.5,
        hole_offset_x: 0,
        hole_offset_y: 0,
        layers: ["top", "bottom"],
      },
      {
        type: "pcb_plated_hole",
        pcb_plated_hole_id: "rotated-pill-8",
        x: 20,
        y: -15,
        shape: "rotated_pill_hole_with_rect_pad",
        hole_shape: "rotated_pill",
        pad_shape: "rect",
        hole_width: 2,
        hole_height: 1,
        hole_ccw_rotation: 120,
        rect_pad_width: 4,
        rect_pad_height: 3,
        rect_ccw_rotation: 30,
        rect_border_radius: 0.5,
        hole_offset_x: 0,
        hole_offset_y: 0,
        layers: ["top", "bottom"],
      },
    ],
  },
}
